### ISSUE TITLE
Release Tarballs

### ISSUE THREAD

**Issue by Areustle** [physicsranger/make4FGLxml#62]
Hey Tyrel,

You should generate release tags and tarballs for the target versions of this code so users can refer back to specific versions over time. Here's an overview of the best-practice.

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by physicsranger** [comment]
Thank you Alex, I appreciate the feedback, advice, and useful links.  I will let you know as soon as I have that implemented.

**Comment by physicsranger** [comment]
Okay, the latest release should now be setup for v1.10.8.  @Areustle , if you can take a look and verify that I didn't misunderstand (I plan to dig more into this topic to make sure I get the most out of it) that would be great and then I will officially close the issue.

**Comment by Areustle** [comment]
Looks good to me. Whenever you want to issue a new release just do the same thing: make a tag and create a release. 

Good job.
