### ISSUE TITLE
Min / Max in PL index for Galactic spectrum correction

### ISSUE THREAD

**Issue by sfegan** [physicsranger/make4FGLxml#64]
https://github.com/physicsranger/make4FGLxml/blob/d222bdb49ac9182317ba145fb87b5d442ad94084/LATSourceModel/src/LATSourceModel/SourceList.py#L477

The PL model that corrects the Galactic diffuse model is created with an index of zero (as it should be), but it has limits on the index of [0,10] .. which means that the index can never allow harder spectra than zero. I would suggest the appropriate limits should be [-1,1] or something like that, to allow the correction to swing both positive and negative from the nominal value.

**Comment by physicsranger** [comment]
Good catch!  Looking at XML files produced from my older version, I did have the min and max matched what you suggested, but in my move to the new code I forgot to ensure that this was done the same way.  I've pushed a change and will upload it to PyPI soon and create a new release tag. (I just have to sort out my PyPI password to verify my email).

**Comment by physicsranger** [comment]
This has been implemented in the latest release (v1.10.10).  The release has been created on GitHub and uploaded to PyPI, available via:
```
python3 -m pip install --upgrade LATSourceModel
```
